-- Categories Table - These are the riddles/puzzles that the player has to solve.
create table public.categories (
  id bigint generated by default as identity not null,
  category text not null,
  constraint categories_pkey primary key (id),
  constraint categories_name_key unique (category)
) TABLESPACE pg_default;

-- Tags Table - These are the tags that we use to choose questions (a different number for each difficulty level).
create table public.tags (
  id bigint generated by default as identity not null,
  tag text not null,
  category_id bigint not null,
  constraint tags_pkey primary key (id),
  constraint tags_category_id_fkey foreign KEY (category_id) references categories (id)
) TABLESPACE pg_default;

-- Terms Table - All the terms in the game (the text on the tiles)
create table public.terms (
  id bigint generated by default as identity not null,
  term text not null,
  category_id bigint not null,
  constraint terms_pkey primary key (id),
  constraint terms_category_id_fkey foreign KEY (category_id) references categories (id)
) TABLESPACE pg_default;

-- And some random views

create view public.random_categories as
select
  categories.id,
  categories.category
from
  categories
order by
  (random());

create view public.random_tags as
select
  tags.id,
  tags.tag,
  tags.category_id
from
  tags
order by
  (random());

create view public.random_terms as
select
  terms.id,
  terms.term,
  terms.category_id
from
  terms
order by
  (random());
